import { test, expect } from '@playwright/test'

test('handbook presents a compact reference and leads into the course', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('link', { name: 'Handbook', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Handbook', exact: true })).toBeVisible()
  await expect(page.locator('.handbook-reference details')).toHaveCount(3)
  await expect(page.getByText('From a click to a new screen')).toHaveCount(0)
  await expect(page.getByText('See it happen')).toHaveCount(0)
  await expect(page.getByText('Check your understanding')).toHaveCount(0)
  await page.locator('.handbook-reference summary').first().click()
  await expect(page.getByText("settings.volume = 75")).toBeVisible()
  await expect(page.getByText("tags.push('Testing')")).toBeVisible()
  await expect(page.getByLabel('Correct object update')).toContainText('...settings')
  await expect(page.getByLabel('Correct array update')).toContainText('...tags')
  await page.getByRole('link', { name: 'Start lesson 1' }).click()
  await expect(page).toHaveURL(/lesson\/1/)
  await page.getByRole('link', { name: 'Handbook', exact: true }).first().click()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Handbook', exact: true })).toBeVisible()
  await expect(page.getByText('0 of 9 complete')).toBeVisible()
})

test('legacy introduction redirects and handbook fits a phone with keyboard-accessible patterns', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./#/introduction')
  await expect(page.getByRole('heading', { name: 'Handbook', exact: true })).toBeVisible()
  await expect(page).toHaveURL(/handbook/)
  const firstPattern = page.locator('.handbook-reference summary').first()
  await firstPattern.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.handbook-reference details').first()).toHaveAttribute('open', '')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
